# Generated by Django 3.2.20 on 2023-09-06 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for answer', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Content of the answer', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title name of the chapter', max_length=200)),
                ('min_correct_ans', models.PositiveIntegerField(help_text='Minimum correct answers to pass the test')),
                ('time_limit', models.TimeField(help_text='Time limit for the test')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Genre of the subject (IT, Japanese, etc)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('c', 'Completed'), ('i', 'Incomplete')], default='i', max_length=1)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.chapter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title name of the subject', max_length=200)),
                ('description', models.TextField(help_text='Description', max_length=1000)),
                ('genres', models.ManyToManyField(help_text='Select genre for this subject', to='main.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for question', primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Detail of the question', max_length=1000)),
                ('corerct_answer', models.UUIDField(help_text='ID for the correct answer')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, choices=[('c', 'Completed'), ('i', 'Incomplete')], default='i', max_length=1)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for answer', primary_key=True, serialize=False)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.test')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
