# Generated by Django 4.2.5 on 2023-09-10 16:07

from django.db import migrations

def forward_func(apps, schema_editor):
    # Add IT and Japanese genres
    Genre = apps.get_model("main", "Genre")
    Genre.objects.bulk_create([
        Genre(name="IT"),
        Genre(name="Japanese"),
    ])

def reverse_func(apps, schema_editor):
    # Remove IT and Japanese genres
    Genre = apps.get_model("main", "Genre")
    Genre.objects.filter(name__in=["IT", "Japanese"]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_auto_20230908_1428"),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
