# Generated by Django 4.2.5 on 2023-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_seed_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="num_questions",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description", max_length=1000
            ),
        ),
    ]
