# Generated by Django 3.2.20 on 2023-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
