# Generated by Django 4.2.5 on 2023-09-12 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_questionsetimport_rename_question_id_answer_question_and_more"),
        ("main", "0007_merge_20230912_1146"),
    ]

    operations = []
