# Generated by Django 4.2.5 on 2023-09-13 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_merge_20230912_1003"),
        ("main", "0008_subject_enrollers"),
    ]

    operations = []
