# Generated by Django 3.2.20 on 2023-09-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_choice_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
