# Generated by Django 3.2.20 on 2023-09-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230914_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='best_score',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='do_times',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='is_passed',
        ),
    ]
