# Generated by Django 3.2.20 on 2023-09-27 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0015_auto_20230914_2050"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intoduction",
                    models.TextField(
                        blank=True, help_text="Introduction", max_length=1000
                    ),
                ),
                ("date_of_birth", models.DateField(help_text="Date of Birth of user")),
                (
                    "avatar",
                    models.ImageField(
                        default="avatars/avatar.png", upload_to="avatars/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
