# Generated by Django 3.2.20 on 2023-09-27 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="intoduction",
            new_name="introduction",
        ),
    ]
