# Generated by Django 3.2.20 on 2023-09-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_rename_intoduction_profile_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/avatar.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Date of Birth of user", null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="Introduction", max_length=1000, null=True
            ),
        ),
    ]
