# Generated by Django 3.2.20 on 2023-09-29 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_add_profiles_to_existing_users"),
        ("main", "0019_alter_profile_introduction"),
    ]

    operations = []
