# Generated by Django 4.2.7 on 2023-12-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_notification_updated_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
